import csv
import os

data = [
    ["symptoms", "recommendation", "diagnosis"],
   ["sudden death", "In the unfortunate event of sudden death among your goats, it is crucial to handle the situation with care and responsibility. Firstly, carefully examine the deceased animal to identify any visible signs of illness or injury. This initial inspection may provide valuable information about the potential cause of death. Subsequently, it is imperative to dispose of the dead animal properly to prevent the spread of diseases and maintain overall herd health. Use protective gear such as gloves to minimize personal contact and follow biosecurity measures.Consider burial as an option, ensuring a sufficient depth to prevent scavengers and meet local regulations. Alternatively, contact your local veterinary authorities for guidance on proper disposal methods, which may include incineration or rendering services. Prompt and appropriate disposal not only mitigates potential health risks but also adheres to ethical and environmental considerations.Simultaneously, investigate the sudden death by consulting with a veterinarian. Conduct a post-mortem examination to identify any internal issues or diseases that may have contributed to the untimely demise. This professional evaluation aids in understanding potential herd health risks and implementing preventive measures.Maintain detailed records of the incident, including the date, observed symptoms, and any veterinary findings. Regularly monitor the health and behavior of the remaining goats, implementing preventive health measures based on the veterinarian's recommendations.Remember, sudden death incidents underscore the importance of proactive herd management, emphasizing regular health checks, vaccinations, and biosecurity practices. By approaching such unfortunate events systematically, you contribute to the well-being and longevity of your goat herd.", 1],
    ["difficulty in breathing", "If you observe goats experiencing difficulty in breathing, it is essential to take immediate action to safeguard their health. Difficulty in breathing, also known as respiratory distress, can indicate various underlying issues, ranging from respiratory infections to environmental factors. To address this concern, avoid grazing your goats in areas where anthrax has been known to occur, as anthrax can lead to severe respiratory problems.Additionally, ensure proper ventilation in your goat housing to minimize the risk of respiratory infections. Provide a clean and dust-free environment, as dusty and unventilated spaces can exacerbate breathing difficulties. Consult with a veterinarian promptly for a comprehensive examination and accurate diagnosis. The vet may recommend appropriate treatment measures, such as administering antibiotics for respiratory infections.Monitor the affected goats closely, observing their breathing patterns, nasal discharge, and overall behavior. Implement isolation measures if necessary to prevent the potential spread of contagious diseases. Stay vigilant for any signs of improvement or deterioration and adjust the treatment plan accordingly.Remember, early intervention is crucial in addressing respiratory issues. By being proactive and seeking professional veterinary care, you contribute to the overall well-being of your goats and prevent potential outbreaks within your herd.", 1],
     ["high fever", "If your goats are experiencing high fever, it is crucial to take immediate steps to ensure their health and well-being. High fever can be indicative of various underlying issues, including infectious diseases such as anthrax. To address this concern, prioritize the health and safety of your goats by considering anthrax vaccination. Anthrax poses a serious threat to livestock, and preventive measures are essential.Consult with a veterinarian to discuss an appropriate vaccination schedule tailored to your goats' needs. Timely immunization can effectively safeguard your herd against anthrax infections, preventing potential outbreaks and ensuring the overall well-being of your animals. Prioritize this preventive measure to promote a healthy and thriving goat population on your farm.In addition to vaccination, closely monitor your goats for any signs of illness, such as changes in behavior, appetite, or physical appearance. If you notice any abnormalities, seek prompt veterinary attention to address potential health issues early on. This proactive approach will contribute to the longevity and productivity of your goat herd.Maintain a clean and hygienic living environment for your goats to reduce the risk of disease transmission. Provide a balanced and nutritious diet to support their immune system and promote optimal growth. Implement proper parasite control measures and practice good biosecurity to prevent the introduction of infectious agents to your herd.By taking comprehensive measures and working closely with a veterinarian, you ensure the health and resilience of your goat herd in the face of high fever and potential anthrax threats.", 1],

    ["swelling", "Vaccinate your goats against anthrax. Swelling in goats can be indicative of various health issues, ranging from infections to injuries. In addition to vaccination, conduct a thorough physical examination of your goats to identify the cause of swelling. Check for any signs of wounds, abscesses, or abnormal growths. If the swelling persists or is accompanied by other symptoms, seek veterinary assistance for a comprehensive diagnosis. Implement appropriate treatment measures based on the underlying cause to alleviate discomfort and promote the recovery of your goats. Maintain a hygienic living environment, and practice proper wound care to prevent infections. Regularly monitor the overall health of your goats to detect and address any health concerns promptly.", 1],
    ["weakness", "Wear gloves and other protective gear when handling dead animals. Weakness in goats can be a symptom of various underlying issues, including nutritional deficiencies, infections, or metabolic disorders. In addition to taking precautions during animal handling, assess your goats' diet to ensure it meets their nutritional requirements. Consult with a veterinarian to develop a balanced and appropriate feeding plan. Address any potential health issues promptly through veterinary care and appropriate treatment. Provide a comfortable and stress-free environment for your goats to support their recovery. Regularly monitor their behavior and physical condition, and seek professional advice if weakness persists or worsens.", 1],
    ["nose discharge and mouth", "Wear gloves and other protective gear when handling dead animals. Nose discharge and mouth-related issues in goats can be indicative of respiratory infections or other health concerns. In addition to taking precautions during animal handling, monitor your goats closely for any signs of respiratory distress, such as coughing or labored breathing. If you observe abnormal discharge from the nose or mouth, consult with a veterinarian for a thorough examination and diagnosis. Implement appropriate treatment measures based on the underlying cause, such as antibiotic therapy for bacterial infections. Maintain proper ventilation in your goat housing to reduce the risk of respiratory issues. Practice good hygiene to minimize the spread of infections among your goat herd.", 1],
    ["no symptom", "It is good that your goat has no visible symptoms. However, it's essential to remain vigilant and regularly monitor your goats for any subtle changes in behavior, appetite, or physical appearance. Even in the absence of visible symptoms, practicing preventive measures is crucial for maintaining the overall health and well-being of your goat herd. Ensure that your goats receive regular veterinary check-ups and vaccinations to safeguard them against potential diseases. Maintain a clean and hygienic living environment, provide a balanced and nutritious diet, and implement proper parasite control measures. By staying proactive in your goat management practices, you contribute to the long-term health and productivity of your goat herd.", 0],
    ["loss of appetite", "If your goat is experiencing a loss of appetite, it may be a sign of an underlying health issue that requires immediate attention. Proper diagnosis and intervention are crucial to prevent further complications and ensure the overall well-being of your goat. To address this concern, consider the following recommendations:\n\n1. Vaccination Against Anthrax:\n   Vaccinate your goats against anthrax, a potential cause of loss of appetite. Consult with a veterinarian to develop an appropriate vaccination schedule tailored to your goats' needs.\n\n2. Regular Veterinary Check-ups:\n   Schedule regular veterinary check-ups to ensure the overall health and well-being of your goats. These check-ups allow early detection of health issues and timely intervention.\n\n3. Clean and Hygienic Living Environment:\n   Maintain a clean and hygienic living environment for your goats. A well-ventilated and sanitized space helps prevent the spread of diseases and promotes good health.\n\n4. Balanced and Nutritious Diet:\n   Provide a balanced and nutritious diet to support your goat's overall health. Consult with a veterinarian or animal nutritionist to create a diet plan that meets your goat's specific nutritional needs.\n\n5. Isolation and Monitoring:\n   If the loss of appetite is accompanied by other symptoms, consider isolating the affected goat to prevent the potential spread of contagious diseases. Monitor its behavior, hydration levels, and any changes in symptoms.\n\n6. Consultation with Veterinarian:\n   Seek prompt veterinary attention for a comprehensive examination and diagnosis. The veterinarian will conduct tests, such as bloodwork or imaging, to identify the underlying cause of the loss of appetite.", 1],

]

# Write to CSV file
csv_file_path = "recom_data.csv"
with open(csv_file_path, mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerows(data)

# Get the size of the file
file_size = os.path.getsize(csv_file_path)

print(f"CSV file '{csv_file_path}' has been created with updated recommendations.")
print(f"File size: {file_size} bytes")
