# Generated by Django 3.2.6 on 2024-01-31 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthraxsymptom',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to='authentication.customuser'),
            preserve_default=False,
        ),
    ]
